kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auth-role-{{ .Release.Name }}
rules:
  - apiGroups: [ "" ]
    resources: [ "services", "configmaps", "secrets","endpoints" ]
    verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-grantor-binding-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auth-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}