apiVersion: v1
kind: Service
metadata:
  name: auth-ui-{{ .Release.Name }}
  labels:
    app: auth-ui-{{ .Release.Name }}
spec:
  ports:
    - port: 80
      targetPort: 80
      name: auth-ui-port
  selector:
    app: auth-ui-{{ .Release.Name }}
  type: ClusterIP